# Generated by Django 4.1.3 on 2023-12-31 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=15, unique=True)),
                ('date_requested', models.DateField()),
                ('borrowed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.05, max_digits=5)),
                ('interest', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_disbursed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField()),
                ('amount_to_be_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_repaid', models.BooleanField(default=False)),
                ('date_repaid', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_loans', to='authentication.member')),
            ],
        ),
        migrations.CreateModel(
            name='BenevolentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_claim_requested', models.DateField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('date_rejected', models.DateField(blank=True, null=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=30)),
                ('bank', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('agreement_checked', models.BooleanField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benevolent_claim', to='authentication.member')),
            ],
        ),
        migrations.CreateModel(
            name='WelfareStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welfare_shares_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('welfare_benevolent_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('welfare_loanInterest_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('welfare_activeMembers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WelfareLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=15, unique=True)),
                ('date_requested', models.DateField()),
                ('borrowed_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('loan_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('total_loan_interest', models.DecimalField(decimal_places=4, default=0.05, max_digits=15)),
                ('installment', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('duration_months', models.IntegerField()),
                ('is_disbursed', models.BooleanField(default=False)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('loan_maturity_date', models.DateField(blank=True, null=True)),
                ('loan_amount_to_be_paid', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('is_repaid', models.BooleanField(default=False)),
                ('date_repaid', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welfare_loans', to='authentication.member')),
            ],
            options={
                'db_table': 'backOffice_WelfareLoan',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_type', models.CharField(choices=[('benovelent', 'Benovelent Contribution'), ('shares', 'Shares Contribution'), ('normal_loan', 'Normal Loan'), ('salary_advance_loan', 'Salary Advance Loan')], max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balanceU', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='authentication.member')),
            ],
        ),
        migrations.CreateModel(
            name='ReducingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('interest', models.DecimalField(decimal_places=4, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=4, max_digits=10)),
                ('installment', models.DecimalField(decimal_places=4, max_digits=10)),
                ('outstanding_loan_principal', models.DecimalField(decimal_places=4, max_digits=10)),
                ('months_remaining', models.IntegerField()),
                ('is_picked', models.BooleanField(default=False)),
                ('date_picked', models.DateField(blank=True, null=True)),
                ('installment_maturity_date', models.DateField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('notpaid', 'Not Paid'), ('granted', 'Granted'), ('rejected', 'Rejected')], default='notpaid', max_length=10)),
                ('welfare_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reducing_table', to='backOffice.welfareloan')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='none', max_length=255)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nhif', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nssf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('welfare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('benovelent', models.DecimalField(decimal_places=2, default=250, max_digits=10)),
                ('loan_wf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='authentication.member')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('member_number', models.CharField(default='0000', max_length=255)),
                ('id_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('signature_status', models.CharField(choices=[('Pending', 'Pending Acceptance'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('loan_type_guaranteed', models.CharField(choices=[('Advance', 'Advance Loan'), ('Normal', 'Normal Loan')], default='none', max_length=10)),
                ('guaranteed_repaid', models.BooleanField(default=False)),
                ('advance_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advance_guarantors', to='backOffice.advanceloan')),
                ('welfare_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welfare_guarantors', to='backOffice.welfareloan')),
            ],
        ),
        migrations.CreateModel(
            name='DeceasedInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_name', models.CharField(max_length=255)),
                ('deceased_id_number', models.CharField(max_length=20)),
                ('relationship_with_member', models.CharField(max_length=255)),
                ('deceased_dob', models.DateField()),
                ('deceased_date_of_death', models.DateField()),
                ('is_claim_approved', models.BooleanField(default=False)),
                ('awarded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('benevolent_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deceased_information', to='backOffice.benevolentclaim')),
            ],
        ),
        migrations.CreateModel(
            name='Benovelent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benov_amount', models.DecimalField(decimal_places=2, default=250, max_digits=10)),
                ('is_approved', models.BooleanField(default=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benovelent', to='authentication.member')),
            ],
        ),
        migrations.CreateModel(
            name='AdjustedShareContributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('new_amount', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_amount', to='authentication.member')),
            ],
        ),
    ]
