# Generated by Django 4.1.3 on 2023-12-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backOffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welfarestatistics',
            name='welfare_activeMembers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='welfarestatistics',
            name='welfare_benevolent_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='welfarestatistics',
            name='welfare_loanInterest_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='welfarestatistics',
            name='welfare_shares_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
