# Generated by Django 5.0 on 2024-01-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backOffice', '0003_alter_advanceloan_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfarestatistics',
            name='welfare_new_acccounts_reg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
