# Generated by Django 5.0 on 2024-01-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backOffice', '0004_welfarestatistics_welfare_new_acccounts_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reducingtable',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('notpaid', 'Not Paid'), ('granted', 'Granted'), ('rejected', 'Rejected'), ('cleared', 'Cleared')], default='notpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='welfareloan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cleared', 'Cleared')], default='pending', max_length=10),
        ),
    ]
