# Generated by Django 5.0 on 2024-01-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backOffice', '0006_guarantor_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welfareloan',
            name='borrowed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='welfareloan',
            name='installment',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='welfareloan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=30),
        ),
        migrations.AlterField(
            model_name='welfareloan',
            name='loan_amount_to_be_paid',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='welfareloan',
            name='loan_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='welfareloan',
            name='total_loan_interest',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=30),
        ),
    ]
