# Generated by Django 5.0 on 2024-01-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backOffice', '0009_alter_reducingtable_status_alter_welfareloan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceloan',
            name='userRepayableRequest',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='welfareloan',
            name='userRepayableRequest',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='advanceloan',
            name='amount_to_be_paid',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='advanceloan',
            name='interest',
            field=models.DecimalField(decimal_places=4, max_digits=100),
        ),
        migrations.AlterField(
            model_name='welfareloan',
            name='loan_amount_to_be_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
