# Generated by Django 5.0 on 2024-01-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backOffice', '0010_advanceloan_userrepayablerequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceloan',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
