"""
Django settings for PVWG project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


#custome user model
AUTH_USER_MODEL = 'authentication.CustomUser'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ck$(xzlk++(q8$o8a%!=equ!a2i21_b-wa7n%dx&hsb&a2!c)k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['hamiscodecraft.co.ke', 'www.hamiscodecraft.co.ke', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 'livereload',
    'django.contrib.staticfiles',
    'rest_framework',
    'crispy_forms',
    'authentication',
    'membersPortal',
    'backOffice',
    'corsheaders',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'livereload.middleware.LiveReloadScript',
]

#rest framework API

#crucial when dealing with cross-origin requests,
#especially in a web application with a separate frontend and backend
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  
]

#authentication and permissions for API
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


ROOT_URLCONF = 'PVWG.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PVWG.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',#new whr psycopg2 is for communication
        'NAME': 'PVWG3',#new
        'USER': 'postgres',#new
        'PASSWORD' : '04116201@Bamba',#new
        'HOST': 'localhost',#new
        'PORT' : '5432' #new
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'PVWG1',
#         'USER': 'hamic',
#         'PASSWORD': '6755@Malindi',
#         'HOST': 'localhost',
#         'PORT': '3307',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }

# ONLINE DB CONNECTION

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'hamiscod_PVWG3',
#         'USER': 'hamiscod_pvwg3adm',
#         'PASSWORD': '04116201@Bamba',
#         'HOST': 'localhost',
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }







# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')
# Media settings
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'sbg108.truehost.cloud'
EMAIL_PORT = 587
EMAIL_USE_TLS = True  
EMAIL_HOST_USER = 'pvwgtestmail@hamiscodecraft.co.ke'
EMAIL_HOST_PASSWORD = '04116201@Bamba'



# I trust this mail finds you well. I am writing to formally request a transfer from the Records Management Unit, Kitui TSO, to the Corporate Data Office at Times Tower.

# Having commenced my journey with a three-month attachment, I was recommended and retained for a one-year internship within the Records Management Unit. Over this period, I have actively contributed to the success of the unit. My achievements include revamping of the Kitui TSO registry and automation of its operations, resulting in a significant enhancement of day-to-day activities' such as documents retrieval and tracking.

# While I appreciate the valuable experience gained in Records Management, my true passion lies in data science and artificial intelligence. I am confident that my proficiency in Python, SQL, and JavaScript, coupled with my background in statistics acquired through my Bachelor of Science degree in statistics, would make a substantial contribution to the Corporate Data Office.

# During the extended period, as indicated in the recent extension letter for six months post-internship, I aim to further hone my skills and knowledge in data science. I am eager to leverage this time to immerse myself in the challenges and opportunities presented by the Corporate Data Office at Times Tower.

# I am actively pursuing additional learning opportunities to expand my expertise in data science, and I am confident that I can swiftly adapt to the specific tools and technologies used within the department, contributing effectively to its success.

# Recognizing the potential need to fill the vacancy within the Records Management Unit promptly, I am committed to facilitating a smooth transition for my successor. I am willing to assist in any way possible to ensure a seamless handover of responsibilities.

# Thank you for your time and consideration. I look forward to the possibility of discussing this opportunity further with you at your earliest convenience.

# Sincerely,

# Issa Katana.