# Generated by Django 4.1.3 on 2023-12-31 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='none', max_length=255, unique=True)),
                ('member_number', models.CharField(default='0000', max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Blocked', 'Blocked')], default='Pending', max_length=20)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=60000, max_digits=10)),
                ('benovelent_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shares_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('normal_loan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('normal_loan_interest', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salary_advance_loan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salary_advance_loan_interest', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('welfare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255)),
                ('onames', models.CharField(max_length=255)),
                ('username', models.CharField(default='none', max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('idnumber', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('position', models.CharField(max_length=255)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to='authentication.member')),
            ],
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofdependant', models.CharField(max_length=255)),
                ('dependantrelationship', models.CharField(max_length=255)),
                ('dependantidnumber', models.CharField(max_length=20)),
                ('dependantcontact', models.CharField(max_length=20)),
                ('is_picked', models.BooleanField(default=False)),
                ('is_deceased', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='authentication.member')),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofnextofkin', models.CharField(max_length=255)),
                ('nextofkinrelationship', models.CharField(max_length=255)),
                ('nextofkinidnumber', models.CharField(max_length=20)),
                ('nextofkincontact', models.CharField(max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='authentication.member')),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('county', models.CharField(max_length=255)),
                ('subcounty', models.CharField(max_length=255)),
                ('ward', models.CharField(max_length=255)),
                ('sublocation', models.CharField(max_length=255)),
                ('residence', models.CharField(default='none', max_length=255)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='authentication.member')),
            ],
        ),
    ]
