# Generated by Django 5.0 on 2024-01-20 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('membersPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsmsverificationcode',
            name='receiver_member',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_verification_codes', to='authentication.member'),
        ),
    ]
