# Generated by Django 5.0 on 2024-01-20 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('membersPortal', '0002_alter_mailsmsverificationcode_receiver_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsmsverificationcode',
            name='receiver_member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='received_verification_codes', to='authentication.member'),
        ),
        migrations.AlterField(
            model_name='mailsmsverificationcode',
            name='sender_member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sent_verification_codes', to='authentication.member'),
        ),
    ]
