# Generated by Django 5.0 on 2024-01-21 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('membersPortal', '0003_alter_mailsmsverificationcode_receiver_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('action_reason', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_manager', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='account_manager', to='authentication.member')),
                ('member', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='target_member', to='authentication.member')),
            ],
        ),
    ]
